spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beman?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8

# 自定义配置
app:
  jwt:
    secret: beman@2023#SecretKey
    expiration: 86400000
  ai:
    emotion-analysis-url: http://localhost:8000/analyze
  cors:
    allowed-origins: http://localhost:8081

logging:
  level:
    root: INFO
    com.beman: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO